### ISSUE TITLE
v0.20.0 replay stops

### ISSUE THREAD

**Issue by KrNel** [Someguy123/steem-docker#12]
The replay stops at around 9%, and nothing more. I am kicked out of the docket logs at that point.

`./run.sh replay`
`docker logs -f witness`

```
1119343ms p2p_plugin.cpp:616            plugin_initialize    ] caught exception 0 exception: unspecified
process exited with: Host not found (authoritative)
    {"message":"Host not found (authoritative)"}
    asio.cpp:88 resolve_handler

    {}
    asio.cpp:168 resolve

    {"endpoint_string":"seed-central.steemit.com:2001"}
    p2p_plugin.cpp:73 resolve_string_to_ip_endpoints while adding seed node seed-central.steemit.com:2001
1119374ms p2p_plugin.cpp:616            plugin_initialize    ] caught exception 0 exception: unspecified
process exited with: Host not found (authoritative)
    {"message":"Host not found (authoritative)"}
    asio.cpp:88 resolve_handler

    {}
    asio.cpp:168 resolve

    {"endpoint_string":"seed-west.steemit.com:2001"}
    p2p_plugin.cpp:73 resolve_string_to_ip_endpoints while adding seed node seed-west.steemit.com:2001
1120286ms rc_plugin.cpp:919             plugin_initialize    ] Initializing resource credit plugin
1120286ms witness_plugin.cpp:648        plugin_initialize    ] Initializing witness plugin
1120286ms webserver_plugin.cpp:311      plugin_initialize    ] configured with 32 thread pool size
1120286ms webserver_plugin.cpp:343      plugin_initialize    ] configured http to listen on 0.0.0.0:8090
1120286ms webserver_plugin.cpp:349      plugin_initialize    ] configured ws to listen on 0.0.0.0:8090
------------------------------------------------------

            STARTING STEEM NETWORK

------------------------------------------------------
initminer public key: STM-----------------------
chain id: 0000000000000000000000000000000000000000000000000000000000000000
blockchain version: 0.20.0
------------------------------------------------------
1120287ms main.cpp:121                  main                 ] Backtrace on segfault is enabled.
1120287ms chain_plugin.cpp:405          plugin_startup       ] Starting chain with shared_file_size: 68719476736 bytes
1120287ms chain_plugin.cpp:483          plugin_startup       ] Replaying blockchain on user request.
1120287ms database.cpp:185              reindex              ] Reindexing Blockchain
1120317ms block_log.cpp:142             open                 ] Log is nonempty
1120317ms block_log.cpp:151             open                 ] Index is nonempty
1120317ms database.cpp:193              reindex              ] Replaying blocks...
1120317ms rc_plugin.cpp:465             operator()           ] Genesis pool_obj is {"id":0,"pool_array":["21640431401",165575358,"16030041350","14426954266915","5122556912307"]}
1120317ms rc_plugin.cpp:401             operator()           ] resource_new_accounts adjustment on block 1: -165574522
   0.385498%   100000 of 25940455   (65530M free)
   0.770996%   200000 of 25940455   (65530M free)
   1.15649%   300000 of 25940455   (65529M free)
   1.54199%   400000 of 25940455   (65528M free)
   1.92749%   500000 of 25940455   (65527M free)
   2.31299%   600000 of 25940455   (65526M free)
   2.69849%   700000 of 25940455   (65524M free)
   3.08399%   800000 of 25940455   (65522M free)
   3.46948%   900000 of 25940455   (65519M free)
1130187ms database.cpp:4708             apply_hardfork       ] HARDFORK 1 at block 905693
1131045ms database.cpp:4708             apply_hardfork       ] HARDFORK 2 at block 934585
1131589ms database.cpp:4708             apply_hardfork       ] HARDFORK 3 at block 953363
1132864ms legacy_asset.hpp:101          unpack               ] unpack legacy serialization 84959911236353
1132864ms legacy_asset.hpp:70           pack                 ] pack legacy serialization 84959911236353
1132864ms legacy_asset.hpp:70           pack                 ] pack legacy serialization 84959911236353
1132864ms legacy_asset.hpp:70           pack                 ] pack legacy serialization 84959911236353
1132864ms steem_evaluator.cpp:100       do_apply             ] Wrong fee symbol in block 994240
1132864ms legacy_asset.hpp:70           pack                 ] pack legacy serialization 84959911236353
1132864ms legacy_asset.hpp:70           pack                 ] pack legacy serialization 84959911236353
1132864ms legacy_asset.hpp:70           pack                 ] pack legacy serialization 84959911236353
   3.85498%   1000000 of 25940455   (65516M free)
1133757ms legacy_asset.hpp:101          unpack               ] unpack legacy serialization 84959911236353
1133757ms legacy_asset.hpp:70           pack                 ] pack legacy serialization 84959911236353
1133757ms legacy_asset.hpp:70           pack                 ] pack legacy serialization 84959911236353
1133757ms legacy_asset.hpp:70           pack                 ] pack legacy serialization 84959911236353
1133757ms steem_evaluator.cpp:100       do_apply             ] Wrong fee symbol in block 1021529
1133757ms legacy_asset.hpp:70           pack                 ] pack legacy serialization 84959911236353
1133757ms legacy_asset.hpp:70           pack                 ] pack legacy serialization 84959911236353
1133757ms legacy_asset.hpp:70           pack                 ] pack legacy serialization 84959911236353
1134412ms database.cpp:4708             apply_hardfork       ] HARDFORK 4 at block 1041497
   4.24048%   1100000 of 25940455   (65514M free)
   4.62598%   1200000 of 25940455   (65513M free)
   5.01148%   1300000 of 25940455   (65512M free)
   5.39698%   1400000 of 25940455   (65510M free)
   5.78247%   1500000 of 25940455   (65508M free)
   6.16797%   1600000 of 25940455   (65506M free)
   6.55347%   1700000 of 25940455   (65504M free)
   6.93897%   1800000 of 25940455   (65500M free)
   7.32447%   1900000 of 25940455   (65497M free)
1165471ms database.cpp:4708             apply_hardfork       ] HARDFORK 5 at block 1934236
   7.70996%   2000000 of 25940455   (65493M free)
   8.09546%   2100000 of 25940455   (65490M free)
   8.48096%   2200000 of 25940455   (65487M free)
   8.86646%   2300000 of 25940455   (65483M free)
   9.25196%   2400000 of 25940455   (65479M free)
   9.63746%   2500000 of 25940455   (65475M free)
```

I was running on v.0.19.12 before this through compiling it myself.

Any idea what can be the reason for the abrupt stop?

Thanks.

**Comment by Someguy123** [comment]
Hi,

I made a mistake and pushed out the fully memory mode to the low memory mode image the other day. I corrected this within a day of publishing it.

Try running `./run.sh install` again to obtain the corrected image. It might be advisable to run `rm -rf /dev/shm/*` prior to replaying again, as there may be problems with the shared memory in HF20.

I would also suggest trying out these settings to improve the replay speed:

**sysctl settings**
```
vm.dirty_background_ratio = 40
vm.dirty_expire_centisecs = 12000
vm.dirty_ratio = 80
vm.dirty_writeback_centisecs = 30000
vm.dirtytime_expire_seconds = 43200
```

explanation: keep more data in cache. only bother writing cache to disk every 300 seconds (100 centisec = 1 sec)

**IO tuning:**
```
# set physical disks to noop scheduler
echo "noop" > /sys/block/sda/queue/scheduler
echo "noop" > /sys/block/sdb/queue/scheduler
# read ahead 5mb (about 39 131kb blocks, or 81x 63kb blocks)
echo 5120 > /sys/block/sda/queue/read_ahead_kb
echo 5120 > /sys/block/sdb/queue/read_ahead_kb
# if you have an mdadm raid, this is one of the few options that can be set on a raid device
echo 5120 > /sys/block/md2/queue/read_ahead_kb
# lower the IO queue size, as steem doesn't seem to make use of it
echo 16 > /sys/block/sda/queue/nr_requests
echo 16 > /sys/block/sdb/queue/nr_requests
```

explanation:
- noop is good for cpu heavy apps (e.g. steem) where it's intermittently reading/writing during replay
- read ahead pre-loads the next blocks. steem only reads 256 sectors (std disk is 512 bytes, so 131kb) at a time, so read ahead will massively reduce the delay between cpu-heavy ops (rc_plugin), and disk-heavy ops.
- steem doesn't really make use of the I/O queue. reducing it can speed things up, since the system doesn't have to manage the large queue

**Comment by KrNel** [comment]
Thanks. I put the `vm.` settings in `/etc/sysctl.conf`

I tried to sudo the IO tuning commands, but I don't have permission.

I deleted the shared_memory.bin in /dev/shm.

I ran `./run.sh install` again, and then `./run.sh replay`, and the same thing is happening.

Any way for me to determine what's going on?

**Comment by Someguy123** [comment]
Most likely your /dev/shm is too small. Use `sudo ./run.sh shm_size 64G`

Check `df -h /dev/shm` - it's recommended to be at least 64gb.

**Comment by Someguy123** [comment]
As for the tuning commands, it's easiest to run them from root, with `sudo su -`.

Alternatively adjust the commands to use sudo tee instead of a redirect. Example:

```
echo "noop" | sudo tee /sys/block/sda/queue/scheduler
```

**Comment by KrNel** [comment]
`df -h /dev/shm`
```
Filesystem      Size  Used Avail Use% Mounted on
tmpfs            65G 1015M   65G   2% /dev/shm
```

I started replaying from 0.19.12 compiled version again, so it's rebuilding the sharedmem file.

So I have an adequate size, yes?

The tuning won't affect the ability to run the node by default. I'd like to understand what's going on... :/

**Comment by Someguy123** [comment]
I'm not really sure what's wrong, we've replayed our seed just fine with the current release of steem-docker. It does look like your /dev/shm is the correct size, assuming you have at least that much RAM.

If you can re-install the latest steem-docker, then put the output of the following commands (after it freezes) on https://gist.github.com it may help me diagnose the problem:

```
docker images
docker ps -a
docker inspect seed
ls -lah /dev/shm
```

Replace `seed` with the name of the container if you've renamed it.

**Comment by KrNel** [comment]
By "re-install the latest steem-docker", is that  `./run.sh install`?

I did it before, and here is the output from those command: https://gist.github.com/KrNel/0e172bdc26e3018d69f59735cdb4c886

Thanks.

**Comment by Someguy123** [comment]
Hmm, I'm not sure what's wrong at this point.

That's the correct image version, and the mount points seem correct.

Can you post the output of these commands:

```
cat /etc/lsb-release
docker -v
ls -la /home/krnel/steem-docker/data
ls -la /home/krnel/steem-docker/data/witness_node_data_dir/blockchain
cat /proc/cpuinfo | tail -n 30
free -m
```

These should get me more information to help me debug why it's not working. I've happily replayed a few servers now with this just fine.

**Comment by KrNel** [comment]
https://gist.github.com/KrNel/e7f74e6aef914f872b153a44b986813e

Since the blockchain files aren't in your docker folder as I'm running the witness node now, they are in `~/.steemd/blockchain`, I gave you that folder info.

Note that although I have only 32GB physical ram, I have zram set up, and it works fine with 0.19.12 compiled. That's not why the replay stops at 9% using your image I don't think...

Thanks!

**Comment by Someguy123** [comment]
Wait, why are they in .steemd? 

steem-docker is set up to replay from data/witness_node_data_dir/blockchain

it's not going to replay from .steemd unless you modify the run.sh file to point /steem at /home/krnel/.steemd

**Comment by Someguy123** [comment]
Also, it looks like your vm.swappiness is too high. That might be a factor. 

HF20 is seemingly slower at replaying than previous versions, so you should be avoiding swap as much as possible. For zram, it'll work with vm.swappiness=10 (no lower than that, to prevent swapping too late).

**Comment by KrNel** [comment]
As I said, I'm running the v0.19.12 compiled version that has the data there. When I try to run your docker, I moved the blockchain data to the relative folder as required. So when I ran your docker, I moved them to your docker data/blockchain folder.

I also could not start your last docker image I tried, I think it was 0.19.6 or 10, I forget, with the same issue at 9% killed, while the compiled versions had no issue. The zram trick works. I've been using it for months. Why would your docker image not even get past a few GBs of use at 9% anyways? It's not relevant to using swap or not, because at that point swap isn't even used. It would be if it actually got large enough to use the swap, then I would understand there being an issue. But as I said, I've been running this for a while now. And was using a former version of your docker image without issues in the past. I don't know what changed on my end or whatnot, sorry.

I have set the vm.swappiness=10.

But as I mentioned, everything works on the compiled version when it's at 60 anyways. That's not the issue. But I'll take any performance improvements gladly ;)

Thanks.

**Comment by sydneyitguy** [comment]
I'm having the same issue stopping at 9.54064% of replaying.
I guess it's potentially an issue with Ubuntu 18.04 LTS?

I'll just re-install everything with 16.04LTS and see what happens.

**Comment by TamirTian** [comment]
I have the same problem of 'latest'

**Comment by TamirTian** [comment]
I found some logs of docker
```
Mar 01 20:44:05 iZ2zeffian74m15kl1bg1mZ dockerd[1241]: time="2019-03-01T20:44:05.800692782+08:00" level=info msg="Processing signal 'terminated'"
Mar 01 20:44:05 iZ2zeffian74m15kl1bg1mZ dockerd[1241]: time="2019-03-01T20:44:05.822088599+08:00" level=info msg="stopping healthcheck following graceful shutdown" module=libcontainerd
Mar 01 20:44:05 iZ2zeffian74m15kl1bg1mZ dockerd[1241]: time="2019-03-01T20:44:05.822126435+08:00" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace
Mar 01 20:44:05 iZ2zeffian74m15kl1bg1mZ dockerd[1241]: time="2019-03-01T20:44:05.822163599+08:00" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace
Mar 01 20:44:05 iZ2zeffian74m15kl1bg1mZ dockerd[1241]: time="2019-03-01T20:44:05.822787295+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc4204648e0, TRANSIENT_FAILURE" module=grpc
Mar 01 20:44:05 iZ2zeffian74m15kl1bg1mZ dockerd[1241]: time="2019-03-01T20:44:05.822814945+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc4204648e0, CONNECTING" module=grpc
Mar 01 20:44:05 iZ2zeffian74m15kl1bg1mZ dockerd[1241]: time="2019-03-01T20:44:05.822811496+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc42020abd0, TRANSIENT_FAILURE" module=grpc
Mar 01 20:44:05 iZ2zeffian74m15kl1bg1mZ dockerd[1241]: time="2019-03-01T20:44:05.822847204+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc42020abd0, CONNECTING" module=grpc
Mar 01 20:44:05 iZ2zeffian74m15kl1bg1mZ systemd[1]: Stopping Docker Application Container Engine...
Mar 01 20:44:06 iZ2zeffian74m15kl1bg1mZ systemd[1]: Stopped Docker Application Container Engine.
-- Reboot --
Mar 01 20:46:40 iZ2zeffian74m15kl1bg1mZ systemd[1]: Starting Docker Application Container Engine...
```
