### ISSUE TITLE
./run.sh replay error

### ISSUE THREAD

**Issue by variouscafe** [Someguy123/steem-docker#13]
I have been good to version 0.19.6
but HF20(latest) version is some error. 
the contents are as follows

./run.sh replay
Removing old container
seed
Running steem with replay...
8c2eba93bd44a7bc12d8d7c1bf3a72b4db9cf80bdbb89e8a8fcc78d559dd0a3c
Started.

docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                       PORTS               NAMES
8c2eba93bd44        steem               "steemd --data-dir=/…"   9 seconds ago       Exited (132) 8 seconds ago                       seed

The docker exited as soon as it starts
Can i found a solution?

**Comment by Someguy123** [comment]
Hi,

I saw you closed the issue. Did you resolve the problem?

**Comment by variouscafe** [comment]
Hi someguy123 
Thanks for your script :) 
steem docker file in hub.docker is same issue. in my environment.
so, i try to ./run.sh build  
the builded docker file is working.. but replay is not finished.. 
I will try to this docker image. 
If some issue, i will contact you. 
Thanks someguy123
