### ISSUE TITLE
would you provide instructions?

### ISSUE THREAD

**Issue by rolfedh** [Someguy123/steem-docker#7]
Would you provide instructions or a link to instructions on how to run this?

**Comment by Someguy123** [comment]
Hi,

The instructions are here: https://steemit.com/steem/@someguy123/your-guide-to-setting-up-a-witness-server-steem-in-a-box-hf19

Though they really need converted into a `README.md` :)

**Comment by rolfedh** [comment]
I'll convert them to the readme.md.
