### ISSUE TITLE
Running into errors during the installation process

### ISSUE THREAD

**Issue by rolfedh** [Someguy123/steem-docker#9]
Following the instructions. Saw an error. Tried resizing an running the commands again. See ***bolded*** highlights below:

rolfedlugy-hegwer at RsMBP in ~/Documents
$ ssh -i "whopah.pem" ubuntu@whatever.compute-1.amazonaws.com
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1041-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

43 packages can be updated.
19 updates are security updates.

Last login: Fri Jan  5 18:43:02 2018 from num.num.num.num

ubuntu@ip-wha-wha-wha-wha:~$ cd steem-docker

ubuntu@ip-wha-wha-wha-wha:~/steem-docker$ ./run.sh install
Loading image from someguy123/steem
Using default tag: latest
latest: Pulling from someguy123/steem
d5c6f90da05d: Pull complete 
1300883d87d5: Pull complete 
c220aa3cfc1b: Pull complete 
2e9398f099dc: Pull complete 
dc27a084064f: Pull complete 
f3e4adbb074a: Pull complete 
5830076acf40: Pull complete 
787ca1f89787: Pull complete 
Digest: sha256:dlsafjhasdkjfldsakjflkjdsalkflasdkjflaskdjf
Status: Downloaded newer image for someguy123/steem:latest
Tagging as steem
Installation completed. You may now configure or run the server

ubuntu@ip-wha-wha-wha-wha:~/steem-docker$ ./run.sh dlblocks
Removing old block log
Download @gtg's block logs...
--2018-01-05 18:46:32--  https://gtg.steem.house/get/blockchain.xz/block_log.xz
Resolving gtg.steem.house (gtg.steem.house)... 51.254.67.207
Connecting to gtg.steem.house (gtg.steem.house)|51.254.67.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14762387884 (14G) [application/octet-stream]
Saving to: ‘/home/ubuntu/steem-docker/data/witness_node_data_dir/blockchain/block_log.xz’

/home/ubuntu/steem-docker/data/witness  38%[============================>                                                ]   5.31G  8.32MB/s    in 8m 52s  

Cannot write to ‘/home/ubuntu/steem-docker/data/witness_node_data_dir/blockchain/block_log.xz’ (Success).
Decompressing block log... this may take a while...
***xz: /home/ubuntu/steem-docker/data/witness_node_data_dir/blockchain/block_log: Write error: No space left on device***
FINISHED. Blockchain downloaded and decompressed
Remember to resize your /dev/shm, and run with replay!
$ ./run.sh shm_size SIZE (e.g. 8G)
$ ./run.sh replay

ubuntu@ip-wha-wha-wha-wha:~/steem-docker$ ./run.sh remote_wallet
docker: ***Error response from daemon:*** write /var/lib/docker/containerd/daemon/io.containerd.metadata.v1.bolt/meta.db: no space left on device: unknown.

ubuntu@ip-wha-wha-wha-wha:~/steem-docker$ ./run.sh shm_size 16G
Setting SHM to 16G
mount: only root can use "--options" option

ubuntu@ip-wha-wha-wha-wha:~/steem-docker$ sudo ./run.sh shm_size 16G
Setting SHM to 16G

ubuntu@ip-wha-wha-wha-wha:~/steem-docker$ ./run.sh replay
Removing old container
***Error: No such container: seed***
Running steem with replay...
411f0440a45051969ea69d392636a42c82a2c327c2f2aa647a03c59cae67c20b
docker: ***Error response from daemon:*** write /var/lib/docker/containerd/daemon/io.containerd.metadata.v1.bolt/meta.db: no space left on device: unknown.
Started.

ubuntu@ip-wha-wha-wha-wha:~/steem-docker$ ./run.sh dlblocks
Removing old block log
Download @gtg's block logs...
--2018-01-05 19:03:42--  https://gtg.steem.house/get/blockchain.xz/block_log.xz
Resolving gtg.steem.house (gtg.steem.house)... 51.254.67.207
Connecting to gtg.steem.house (gtg.steem.house)|51.254.67.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14762387884 (14G) [application/octet-stream]
Saving to: ‘/home/ubuntu/steem-docker/data/witness_node_data_dir/blockchain/block_log.xz’

/home/ubuntu/steem-docker/data/witness  38%[============================>                                                ]   5.31G  10.9MB/s    in 6m 40s  

Cannot write to ‘/home/ubuntu/steem-docker/data/witness_node_data_dir/blockchain/block_log.xz’ (Success).
Decompressing block log... this may take a while...
xz: /home/ubuntu/steem-docker/data/witness_node_data_dir/blockchain/block_log: ***Write error: No space left on device***
FINISHED. Blockchain downloaded and decompressed
Remember to resize your /dev/shm, and run with replay!
$ ./run.sh shm_size SIZE (e.g. 8G)
$ ./run.sh replay

ubuntu@ip-wha-wha-wha-wha:~/steem-docker$ ./run.sh shm_size 16G
Setting SHM to 16G
mount: only root can use "--options" option

ubuntu@ip-wha-wha-wha-wha:~/steem-docker$ sudo ./run.sh shm_size 16G
Setting SHM to 16G

ubuntu@ip-wha-wha-wha-wha:~/steem-docker$ sudo ./run.sh replay
Removing old container
seed
Running steem with replay...
74449414addc0ecd8e6591ceed584957b808eab2e2ce772809fd293a742b907b
docker: ***Error response from daemon:*** mkdir /var/lib/docker/containers/74449414addc0ecd8e6591ceed584957b808eab2e2ce772809fd293a742b907b/shm: ***no space left on device.***
Started.

ubuntu@ip-wha-wha-wha-wha:~/steem-docker$

**Comment by Someguy123** [comment]
The error is pretty clear with "no space left on device".

Be aware that AWS no longer includes SSD space on most of their instances...

You may need to change docker settings to put onto EBS or similar.

**Comment by rolfedh** [comment]
I was using an AWS instance with EBS. I'll try one with an SSD. Should we site SSD in the hardware requirements?
